# Generated by Django 4.0.4 on 2022-11-28 10:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
